---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: gnupg, tags: ['gnupg'] }
    - { role: sysmon, tags: ['sysmon'] }
    - { role: cron, tags: ['cron'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: hardened, tags: ['hardened'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: x, tags: ['x'] }
    - { role: alacritty, tags: ['alacritty'] }
    - { role: lightdm, tags: ['lightdm'], when: "display_manager == 'lightdm'" }
    - { role: i3, tags: ['i3'], when: "desktop_environment == 'i3'" }
    - { role: pass, tags: ['pass'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: nmtrust, tags: ['nmtrust'] }
    - { role: unbound, tags: ['unbound'] }
    - { role: openresolv, tags: ['openresolv'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: macchiato, tags: ['macchiato'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: firejail, tags: ['firejail'] }
    - { role: tor, tags: ['tor'], when: "tor is defined" }
    - { role: editors, tags: ['editors'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
    - { role: optical, tags: ['optical'] }
    - { role: udisks, tags: ['udisks'] }
    - { role: spell, tags: ['spell'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: yubikey, tags: ['yubikey'] }
    - { role: media, tags: ['media'] }
    - { role: mpd, tags: ['mpd'] }
    - { role: mpv, tags: ['mpv'] }
    - { role: pianobar, tags: ['pianobar'] }
    - { role: laptop, tags: ['laptop'] }
    - { role: thinkpad, tags: ['thinkpad'], when: "'ThinkPad' in ansible_product_version" }
    - { role: macbook, tags: ['macbook'], when: "'MacBook' in ansible_product_name" }
    - { role: screensaver, tags: ['screensaver'] }
    - { role: weechat, tags: ['weechat'] }
    - { role: taskwarrior, tags: ['taskwarrior'] }
    - { role: ledger, tags: ['ledger'] }
    - { role: mail, tags: ['mail'] }
    - { role: cups, tags: ['cups'] }
    - { role: office, tags: ['office'] }
    - { role: visidata, tags: ['visidata'] }
    - { role: pdf, tags: ['pdf'] }
    - { role: dictd, tags: ['dictd'] }
    - { role: redshift, tags: ['redshift'] }
    - { role: transmission, tags: ['transmission'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    - { role: hashicorp, tags: ['hashicorp'] }
    - { role: virtualenv, tags: ['virtualenv'] }
    - { role: mapping, tags: ['mapping'] }
    - { role: sound, tags: ['sound'] }
    - { role: pim, tags: ['pim'] }
    - { role: radio, tags: ['radio'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: calibre, tags: ['calibre'] }
    - { role: parcimonie, tags: ['parcimonie'], when: "tor is defined" }
    - { role: localtime, tags: ['localtime'], when: "localtime is defined" }
    - { role: wormhole, tags: ['wormhole'] }
#    - { role: bluetooth, tags: ['bluetooth'], when: "bluetooth is defined" }
    - { role: wttr, tags: ['wttr'] }
    - { role: syncthing, tags: ['syncthing'], when: "syncthing is defined" }
    - { role: mirrorlist, tags: ['mirrorlist'], when: "mirrorlist is defined" }
    - { role: pkgfile, tags: ['pkgfile'], when: "pkgfile is defined" }
    - { role: units, tags: ['units'], when: "units is defined" }
    - { role: logitech, tags: ['logitech'] }
    - { role: pydev, tags: ['pydev'] }
    - { role: signal, tags: ['signal'] }
    - { role: ripgrep, tags: ['ripgrep'] }
    - { role: zeal, tags: ['zeal'] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
