---
- name: Install Zathura and dependencies
  pacman:
    name:
      - zathura
      - zathura-cb
      - zathura-djvu
      - zathura-ps
    state: present
  tags:
    - zathura

- name: Set Zathura as default PDF viewer
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "^application/pdf"
    state: present
    line: "application/pdf=org.pwmt.zathura.desktop"
  tags:
    - zathura

- name: Install pdfgrep
  pacman:
    name: pdfgrep
    state: present
  tags:
    - pdfgrep
