---
- name: Install Zathura and dependencies
  pacman:
    name:
      - zathura
      - zathura-cb
      - zathura-djvu
      - zathura-ps
    state: present
  tags:
    - zathura

- name: Install pdfgrep
  pacman:
    name: pdfgrep
    state: present
  tags:
    - pdfgrep
