---
- name: Install dictd
  pacman:
    name: dictd
    state: present

- name: Install flex
  pacman:
    name: flex
    state: present

- name: Install GNU Collaborative International Dictionary of English
  aur:
    name: dict-gcide
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - aur

- name: Install WordNet database
  aur:
    name: dict-wn
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install gcide database
  aur:
    name: dict-gcide
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install freedict deu -> eng
  aur:
    name: dict-freedict-deu-eng-bin
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install freedict fra -> eng
  aur:
    name: dict-freedict-fra-eng-bin
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install freedict isl -> eng
  aur:
    name: dict-freedict-isl-eng-bin
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install freedict jpn -> eng
  aur:
    name: dict-freedict-jpn-eng-bin
    user: "{{ user.name }}"
  tags:
    - aur


- name: Install wiktionary (en)
  aur:
    name: dict-wikt-en-all
    user: "{{ user.name }}"
  tags:
    - aur

- name: Enable and start dictd
  service:
    name: dictd.service
    enabled: yes
    state: started
