---
- name: Install pass
  pacman:
    name: pass
    state: present

- name: Install pass-update
  aur:
    name: pass-update
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - aur

- name: Install xkcdpass
  aur:
    name: xkcdpass
    user: "{{ user.name }}"
  tags:
    - aur
