---
- name: Install mpd
  pacman: name=mpd state=present

- name: Push mpd service file
  copy: src=mpd.service dest=/etc/systemd/user/mpd.service
  notify:
    - reload systemd config

- name: Install mpc
  pacman: name=mpc state=present

- name: Install ncmpc
  pacman: name=ncmpc state=present
