---
- name: Install command line tools from repos
  pacman:
    name:
    - exa
    state: present

- name: Install command line tools from AUR
  aur:
    name:
    - autojump
    - di
    user: "{{ user.name }}"
  tags:
    - aur
