---
- name: Install command line tools
  pacman:
    name:
    - di
    state: present

- name: Install command line tools from AUR
  aur:
    name:
    - autojump
    user: "{{ user.name }}"
  tags:
    - aur
