---
- name: Install hunspell
  pacman:
    name:
      - hunspell
      - hunspell-de
      - hunspell-en_gb
      - hunspell-en_us
    state: present
  tags:
    - hunspell

- name: Install aspell
  pacman:
    name:
      - aspell
      - aspell-de
      - aspell-en
    state: present
  tags:
    - aspell
