---
- name: Install feh
  pacman: name=feh state=present
  tags:
    - feh

- name: Install imlib2-heic
  aur:
    name: imlib2-heic
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - aur
    - feh
