---
- include: beets.yml
- include: imagemagick.yml
- include: feh.yml

- name: Install misc media codecs and helpers
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - opus-tools
    state: present

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present

- name: Install flameshot
  pacman:
    name: flameshot
    state: present
