---
- name: Install zip archive utilities
  pacman:
    name:
      - zip
      - unzip
      - p7zip
    state: present
  tags:
    - zip

- name: Install unrar
  pacman:
    name: unrar
    state: present
  tags:
    - unrar

- name: Install par2cmdline
  pacman:
    name: par2cmdline
    state: present
  tags:
    - par2
